name: Atualizar tabela Brasileirão

on:
  schedule:
    - cron: '0 3 * * *'  # Roda todo dia às 03:00 AM UTC (~meia-noite no Brasil)
  workflow_dispatch:     # Permite rodar manualmente pelo GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checar código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Rodar scraper e gerar HTML
      run: |
        python gerar_tabela.py

    - name: Commit e push do index.html atualizado
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add index.html
        git commit -m "Atualização automática da tabela"
        git push
      continue-on-error: true
